edition = "2021"
brace_style = "SameLineWhere"
comment_width = 80
condense_wildcard_suffixes = true
doc_comment_code_block_width = 80
fn_single_line = true
force_explicit_abi = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = false
imports_granularity = "Crate"
indent_style = "Block"
max_width = 80
merge_derives = true
newline_style = "Auto"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = false
